/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package co.makerflow.client.apis

import co.makerflow.client.models.LogProductiveActivity200Response

import co.makerflow.client.infrastructure.*
import io.ktor.client.HttpClientConfig
import io.ktor.client.request.forms.formData
import io.ktor.client.engine.HttpClientEngine
import io.ktor.http.ParametersBuilder
import com.fasterxml.jackson.databind.ObjectMapper

    open class ProductiveActivityApi(
    baseUrl: String = ApiClient.BASE_URL,
    httpClientEngine: HttpClientEngine? = null,
    httpClientConfig: ((HttpClientConfig<*>) -> Unit)? = null,
    jsonBlock: ObjectMapper.() -> Unit = ApiClient.JSON_DEFAULT,
    ) : ApiClient(baseUrl, httpClientEngine, httpClientConfig, jsonBlock) {

        /**
        * 
        * 
         * @param requestBody Productive activity to be logged 
         * @param source To specify source of request (optional)
         * @return LogProductiveActivity200Response
        */
            @Suppress("UNCHECKED_CAST")
        open suspend fun logProductiveActivity(requestBody: kotlin.collections.List<kotlin.Long>, source: kotlin.String?): HttpResponse<LogProductiveActivity200Response> {

            val localVariableAuthNames = listOf<String>("api_token")

            val localVariableBody = requestBody

            val localVariableQuery = mutableMapOf<String, List<String>>()
            source?.apply { localVariableQuery["source"] = listOf("$source") }

            val localVariableHeaders = mutableMapOf<String, String>()

            val localVariableConfig = RequestConfig<kotlin.Any?>(
            RequestMethod.POST,
            "/productive-activity",
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = true,
            )

            return jsonRequest(
            localVariableConfig,
            localVariableBody,
            localVariableAuthNames
            ).wrap()
            }

        }
