/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package co.makerflow.client.models

import co.makerflow.client.models.CustomTask

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * A custom task todo
 *
 * @param task
 * @param sourceType The type of source that the todo is from
 * @param type The type of todo
 * @param createdAt Timestamp for when the todo was created
 * @param done Whether the todo has been completed
 */


data class CustomTaskTodo (

    @field:JsonProperty("task")
    val task: CustomTask,


): TypedTodo()

