/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package co.makerflow.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * A custom task
 *
 * @param id The id of the custom task
 * @param title Title for task
 * @param createdAt Timestamp for when the custom task was created
 * @param done Whether the custom task has been completed
 * @param userId The id of the user that created the custom task
 * @param updatedAt Timestamp for when the custom task was last updated
 */


data class CustomTask (

    /* The id of the custom task */
    @field:JsonProperty("id")
    val id: kotlin.Int? = null,

    /* Title for task */
    @field:JsonProperty("title")
    val title: kotlin.String? = null,

    /* Timestamp for when the custom task was created */
    @field:JsonProperty("created_at")
    val createdAt: kotlin.String? = null,

    /* Whether the custom task has been completed */
    @field:JsonProperty("done")
    val done: kotlin.Boolean? = null,

    /* The id of the user that created the custom task */
    @field:JsonProperty("user_id")
    val userId: kotlin.Int? = null,

    /* Timestamp for when the custom task was last updated */
    @field:JsonProperty("updated_at")
    val updatedAt: kotlin.String? = null

)

