/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package co.makerflow.client.models


import com.fasterxml.jackson.annotation.JsonIgnoreProperties
import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Objet represent a break from work that has ended
 *
 * @param id
 * @param userId
 * @param start Timestamp for when the break was started
 * @param end Timestamp for when the break was ended
 * @param reason Reason for taking the break
 */


@JsonIgnoreProperties(ignoreUnknown = true)
data class EndedWorkBreak(

    @field:JsonProperty("id")
    val id: kotlin.Int,

    @field:JsonProperty("user_id")
    val userId: kotlin.Int,

    /* Timestamp for when the break was started */
    @field:JsonProperty("start")
    val start: kotlin.String,

    /* Timestamp for when the break was ended */
    @field:JsonProperty("end")
    val end: kotlin.String?,

    /* Reason for taking the break */
    @field:JsonProperty("reason")
    val reason: kotlin.String

)

