/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package co.makerflow.client.models

import co.makerflow.client.models.SlackEvent

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * A collection of slack events
 *
 * @param group 
 * @param type 
 * @param sourceType 
 * @param events 
 * @param createdAt 
 */


data class GroupedSlackEvent (

    @field:JsonProperty("group")
    val group: kotlin.String? = null,

    @field:JsonProperty("type")
    val type: GroupedSlackEvent.Type? = null,

    @field:JsonProperty("sourceType")
    val sourceType: GroupedSlackEvent.SourceType? = null,

    @field:JsonProperty("events")
    val events: kotlin.collections.List<SlackEvent>? = null,

    @field:JsonProperty("created_at")
    val createdAt: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: channel,im,mpim
     */
    enum class Type(val value: kotlin.String) {
        @JsonProperty(value = "slack_channel") channel("slack_channel"),
        @JsonProperty(value = "slack_im") im("slack_im"),
        @JsonProperty(value = "slack_mpim") mpim("slack_mpim");
    }
    /**
     * 
     *
     * Values: slack
     */
    enum class SourceType(val value: kotlin.String) {
        @JsonProperty(value = "slack") slack("slack");
    }
}

