/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package co.makerflow.client.models

import co.makerflow.client.models.MarkDone200ResponseTodo

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param todo 
 */


data class MarkDone200Response (

    @field:JsonProperty("todo")
    val todo: MarkDone200ResponseTodo? = null

)

