/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package co.makerflow.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Error when request method is not supported
 *
 * @param message Description of error
 */


data class MethodNotSupportedException (

    /* Description of error */
    @field:JsonProperty("message")
    val message: kotlin.String? = null

)

