/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package co.makerflow.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param type 
 * @param sourceType 
 * @param createdAt 
 * @param step 
 * @param done 
 */


data class OnboardingTask (

    @field:JsonProperty("type")
    val type: OnboardingTask.Type? = null,

    @field:JsonProperty("sourceType")
    val sourceType: OnboardingTask.SourceType? = null,

    @field:JsonProperty("createdAt")
    val createdAt: kotlin.String? = null,

    @field:JsonProperty("step")
    val step: OnboardingTask.Step? = null,

    @field:JsonProperty("done")
    val done: kotlin.Boolean? = null

) {

    /**
     * 
     *
     * Values: onboarding
     */
    enum class Type(val value: kotlin.String) {
        @JsonProperty(value = "onboarding") onboarding("onboarding");
    }
    /**
     * 
     *
     * Values: makerflow
     */
    enum class SourceType(val value: kotlin.String) {
        @JsonProperty(value = "makerflow") makerflow("makerflow");
    }
    /**
     * 
     *
     * Values: chatMinusIntegration,repoMinusIntegration,calendarMinusIntegration,cliMinusDownload,editorMinusIntegration,browserMinusExtension
     */
    enum class Step(val value: kotlin.String) {
        @JsonProperty(value = "chat-integration") chatMinusIntegration("chat-integration"),
        @JsonProperty(value = "repo-integration") repoMinusIntegration("repo-integration"),
        @JsonProperty(value = "calendar-integration") calendarMinusIntegration("calendar-integration"),
        @JsonProperty(value = "cli-download") cliMinusDownload("cli-download"),
        @JsonProperty(value = "editor-integration") editorMinusIntegration("editor-integration"),
        @JsonProperty(value = "browser-extension") browserMinusExtension("browser-extension");
    }
}

