/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package co.makerflow.client.models

import co.makerflow.client.models.FlowMode

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * A response from Productive API
 *
 * @param success 
 * @param flowModeAlreadyOngoing 
 * @param flow 
 */


data class ProductiveActivityResponse (

    @field:JsonProperty("success")
    val success: kotlin.Boolean? = null,

    @field:JsonProperty("flowModeAlreadyOngoing")
    val flowModeAlreadyOngoing: kotlin.Boolean? = null,

    @field:JsonProperty("flow")
    val flow: FlowMode? = null

)

