/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package co.makerflow.client.models

import co.makerflow.client.models.PullRequest
import co.makerflow.client.models.PullRequestTodoMeta

import com.fasterxml.jackson.annotation.JsonProperty

/**
 * A pull request that needs to be reviewed by the user
 *
 * @param sourceType The type of source that the todo is from
 * @param type
 * @param createdAt Timestamp for when the todo was created
 * @param done Whether the todo has been completed
 * @param pr
 * @param meta
 */


data class PullRequestTodo(

    @field:JsonProperty("pr")
    val pr: PullRequest? = null,

    @field:JsonProperty("meta")
    val meta: PullRequestTodoMeta? = null

): TypedTodo()

