/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package co.makerflow.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * 
 *
 * @param comments 
 * @param approvals 
 */


data class PullRequestTodoMeta (

    @field:JsonProperty("comments")
    val comments: kotlin.Int? = null,

    @field:JsonProperty("approvals")
    val approvals: kotlin.Int? = null

)

