/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package co.makerflow.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * An event from Slack (message in a channel, direct message, private group message
 *
 * @param id 
 * @param userId 
 * @param eventId 
 * @param teamId 
 * @param channelType 
 * @param done 
 * @param channelId 
 * @param channelName 
 * @param senderId 
 * @param botId 
 * @param ts 
 * @param threadTs 
 * @param createdAt 
 * @param updatedAt 
 */


data class SlackEvent (

    @field:JsonProperty("id")
    val id: kotlin.Int? = null,

    @field:JsonProperty("user_id")
    val userId: kotlin.Int? = null,

    @field:JsonProperty("event_id")
    val eventId: kotlin.String? = null,

    @field:JsonProperty("team_id")
    val teamId: kotlin.String? = null,

    @field:JsonProperty("channel_type")
    val channelType: SlackEvent.ChannelType? = null,

    @field:JsonProperty("done")
    val done: kotlin.Boolean? = null,

    @field:JsonProperty("channel_id")
    val channelId: kotlin.String? = null,

    @field:JsonProperty("channel_name")
    val channelName: kotlin.String? = null,

    @field:JsonProperty("sender_id")
    val senderId: kotlin.String? = null,

    @field:JsonProperty("bot_id")
    val botId: kotlin.String? = null,

    @field:JsonProperty("ts")
    val ts: kotlin.Int? = null,

    @field:JsonProperty("thread_ts")
    val threadTs: kotlin.Int? = null,

    @field:JsonProperty("created_at")
    val createdAt: kotlin.String? = null,

    @field:JsonProperty("updated_at")
    val updatedAt: kotlin.String? = null

) {

    /**
     * 
     *
     * Values: channel,im,mpim
     */
    enum class ChannelType(val value: kotlin.String) {
        @JsonProperty(value = "channel") channel("channel"),
        @JsonProperty(value = "im") im("im"),
        @JsonProperty(value = "mpim") mpim("mpim");
    }
}

