/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package co.makerflow.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * A todo task
 *
 * @param sourceType The type of source that the todo is from
 * @param type The type of todo
 * @param createdAt Timestamp for when the todo was created
 * @param done Whether the todo has been completed
 */


data class Todo (

    /* The type of source that the todo is from */
    @field:JsonProperty("sourceType")
    val sourceType: kotlin.String? = null,

    /* The type of todo */
    @field:JsonProperty("type")
    val type: kotlin.String? = null,

    /* Timestamp for when the todo was created */
    @field:JsonProperty("createdAt")
    val createdAt: kotlin.String? = null,

    /* Whether the todo has been completed */
    @field:JsonProperty("done")
    val done: kotlin.Boolean? = null

)

