/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package co.makerflow.client.models

import co.makerflow.client.models.CustomTask
import co.makerflow.client.models.CustomTaskTodo
import co.makerflow.client.models.OnboardingTask
import co.makerflow.client.models.PullRequest
import co.makerflow.client.models.PullRequestTodo
import co.makerflow.client.models.PullRequestTodoMeta

import com.fasterxml.jackson.annotation.JsonProperty
import com.fasterxml.jackson.annotation.JsonSubTypes
import com.fasterxml.jackson.annotation.JsonTypeInfo

/**
 *
 *
 * @param task
 * @param sourceType The type of source that the todo is from
 * @param type The type of todo
 * @param createdAt Timestamp for when the todo was created
 * @param done Whether the todo has been completed
 * @param step
 * @param pr
 * @param meta
 */
@Suppress("ConvertSecondaryConstructorToPrimary")
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = JsonTypeInfo.As.PROPERTY, property = "type", visible = true)
@JsonSubTypes(
    JsonSubTypes.Type(value = PullRequestTodo::class, name = "bitbucket"),
    JsonSubTypes.Type(value = PullRequestTodo::class, name = "github"),
    JsonSubTypes.Type(value = CustomTaskTodo::class, name = "makerflow"),
    JsonSubTypes.Type(value = OnboardingTask::class, name = "onboarding")
)

open class TypedTodo {

    /* The type of source that the todo is from */
    @get:JsonProperty("sourceType")
    var sourceType: TypedTodo.SourceType? = null
    /* The type of todo */
    @get:JsonProperty("type")
    var type: kotlin.String? = null
    /* Timestamp for when the todo was created */
    @get:JsonProperty("createdAt")
    var createdAt: kotlin.String? = null
    /* Whether the todo has been completed */
    @get:JsonProperty("done")
    var done: kotlin.Boolean? = null

    /**
     * The type of source that the todo is from
     *
     * Values: slack,github,bitbucket,makerflow
     */
    @Suppress("EnumNaming")
    enum class SourceType(val value: kotlin.String) {
        @JsonProperty(value = "slack") slack("slack"),
        @JsonProperty(value = "github") github("github"),
        @JsonProperty(value = "bitbucket") bitbucket("bitbucket"),
        @JsonProperty(value = "makerflow") makerflow("makerflow");
    }

}

