/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package co.makerflow.client.models

import com.fasterxml.jackson.annotation.JsonProperty

/**
 *
 *
 * @param events
 */


data class UpcomingCalendarEvents200Response (

    @field:JsonProperty("events")
    val events: kotlin.collections.List<CalendarEvent>? = null

)

