/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package co.makerflow.client.models


import com.fasterxml.jackson.annotation.JsonProperty

/**
 * Object representing a break from work
 *
 * @param id 
 * @param userId 
 * @param start Timestamp for when the break was started
 * @param reason Reason for taking the break
 * @param end Timestamp for when the break was ended
 */


data class WorkBreak (

    @field:JsonProperty("id")
    val id: kotlin.Int,

    @field:JsonProperty("user_id")
    val userId: kotlin.Int,

    /* Timestamp for when the break was started */
    @field:JsonProperty("start")
    val start: kotlin.String,

    /* Reason for taking the break */
    @field:JsonProperty("reason")
    val reason: kotlin.String,

    /* Timestamp for when the break was ended */
    @field:JsonProperty("end")
    val end: kotlin.String? = null

)

